version: '3'
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - database
      - selenium
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWD: postgres
      POSTGRES_HOST: database
      SELENIUM_DRIVER_URL: selenium

  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - '4444:4444'
